### ISSUE TITLE
Motor Conundrum

### ISSUE THREAD

**Issue by fishnsotong** [ocean-x/erikson-1#2]
We've a problem here today, folks. 

The motors that we've bought, seem to be ordinary DC motors, since brushless motors require tri-phase AC current. Therefore we've dumped a small _boatload_ of money on motors that might potentially not work. 

The good news is that we've bought a DC brushless motor with an ESC. I've been told that it can take up to 7.4V, however I have yet to test the current and voltage draw. They seem to be fully waterproof, judging from past work done by others. 

The bad news is that they are rather expensive, and we might not be able to afford many because just to set up one, has cost almost $100. That's not surprising, considering that's how much people spend on aerial drones. We can look into cheaper online alternatives but we will have to wait for them. 

One option is that instead of using two motors for the translational motion, we can use just one motor with a rudder. Submarines have rudders. However, we will be sacrificing maneuverability and lateral rotation. 

The other option is that we use the DC motors, but we somehow remove the pulley drums at the shafts, and manage to waterproof them. Waterproofing them would require 3D-printed canisters, and the usage of insulation tape, silicone and epoxy resin to seal the shaft. (These are all on the printouts.)

Can I have your thoughts on how we should proceed?

**Comment by IvanFengJK** [comment]
Personally, I think it will be better to try to raise fund to buy more expensive motors which are waterproof. To me, the second option is full of uncertainty and risk which may also incur additional cost. Though the first option will have to sacrifice manoeuvrability and lateral rotation, proper explanation and clarifying that it is at the developing stage should not be a problem and existing models of submarines do have rudders too. At the same time, do take note also, future improvement may need to rebuild one with better motors.

**Comment by Retrozir** [comment]
So an expensive, seemingly fully-waterproof and tested brushless DC motor with ESC has already been bought and one of the options is to have a rudder which only utilizes one motor? Sounds like we should go down that route if you ask me. Like Ivan said, though we may need to sacrifice manoeuvrability, this is the first attempt at an underwater ROV and improvements can be made in the future.

**Comment by fishnsotong** [comment]
@Retrozir okay...but I'm all for looking to get cheaper stuff online. Apparently hobbyking has reasonable prices. We should check it out.

Below is the first installment of a series of videos someone posted online about them making an ROV like ours, go check it out. 

https://www.youtube.com/watch?v=HMjzz5UgVXM

**Comment by fishnsotong** [comment]
@Retrozir I agree with your points on the rudder, but I'd like to add that removing the metal pulley drums would be a hassle. 

Given that we have purchased the brushless motors from online, and our budget insofar has been stretched beyond recognition, there really is no need to fret anymore I guess. Thank you everyone for contributing.
