### ISSUE TITLE
Buying Motors, ESCs, Cameras, Sensors

### ISSUE THREAD

**Issue by Swordwrath** [ocean-x/erikson-1#3]
I've looked online and I found an ESC for under $10 each.

http://www.hobbyking.com/hobbyking/store/__11616__Turnigy_AE_25A_Brushless_ESC.html
http://www.hobbyking.com/hobbyking/store/__11615__Turnigy_AE_20A_Brushless_ESC.html

(25A and 20A versions. Our 1.1Ah 20C rated Lipo can discharge a max of 22A @ 11.1V for 3 minutes)

And a few motors for around $10..

http://www.hobbyking.com/hobbyking/store/__9068__Turnigy_1220_Brushless_Inrunner_Motor_10300kv.html
http://www.hobbyking.com/hobbyking/store/__17231__Turnigy_2226_3000_70mm_EDF_Outrunner_.html
http://www.hobbyking.com/hobbyking/store/__21974__Turnigy_Aerodrive_DST_1200_Brushless_Outrunner_motor_1200kv.html

(Outrunner/Inrunner basically means whether the shaft spins or the body spins. Inrunner = high rpm, outrunner = high torque. Ours is an Outrunner, I believe. Also, interestingly enough, hobbyking offers an offer for the product when you stay on that page long enough.)

I'm looking closely at the prices, because at this point, we might even be able to accommodate the 6 motors. So ESC + Motor = $ 20. 4 Motors =$80, 6 Motors =$120. Also, keep in mind that we have the motor Wayne used for his competition, and we might be able to utilize it somehow, and the ESC + Motor we already have.

It is also important to take note that 4/6 ESCS will take up quite a lot of space in the housing chamber. The 12/18 of 12-gauge AWG wires used by the ESCs will also require a hole of significant diameter, so we might have to drill another, bigger hole onto the housing chamber exclusively for wiring the motors, and independent of the tether.

However, now that we have decided to abandon the motor shield, do we have to buy separate accelerometer, gyroscope, and compass? or will we still use the motor board solely for the purpose of functioning as a sensor board?

Anyhow, I've also looked up some cameras for pretty good prices, ($50 - <$70)

http://www.hobbyking.com/hobbyking/store/__62530__Turnigy_HD_ActionCam_1080P_Full_HD_Video_Camera_w_Waterproof_Case.html
http://www.hobbyking.com/hobbyking/store/__88674__RunCam_FULL_HD_1080P_120_degree_FPV_CAMERA_DC_5V_.html

And the pH sensor for SGD40..

http://www.dfrobot.com/index.php?route=product/product&product_id=1025#.V2zzQ7h95hE

So the way it is right now, all we have to do is order most of the stuff from hobbyking and the pH sensor from dfrobot. Around $200 should suffice.

Thoughts?

**Comment by fishnsotong** [comment]
Yay! So the $10 prediction was right, okay. We just need compatible motors with the same kV rating and compatible propellers. Then we need to figure out how to mount and whether we need to pot them. 

@jengheng sir, your thoughts?

**Comment by Swordwrath** [comment]
@fishnsotong Yeah but I couldn't find the same motor that you had so we might still have to buy 4(or 6) to prevent any imbalance in thrust. It's cheap, so we *could* buy 4/6 motors bu then what do we do with the one we have and the blue one?

And what about the state of the motorboard?

**Comment by fishnsotong** [comment]
Do nothing with them? I have no clue, the blue one was actually glued together to be very frank. 

The motor shield isn't really _abandoned_ per se, it's only because the motors are tri-phase, and require a discretised sine wave to run on. We could still use it for a servo and stuff like that.

**Comment by fishnsotong** [comment]
By today, we should've finished purchasing everything, right?
