### ISSUE TITLE
pH Sensor

### ISSUE THREAD

**Issue by fishnsotong** [ocean-x/erikson-1#4]
Anyone can find pH sensor links and send them here so we can evaluate them in a list? Thanks!

**Comment by IvanFengJK** [comment]
Quoted online " As far as I know, the pH is a bit tricky to measure, for most Temp/hum situations there are digital sensors capable to be wired directly to the Pi, but the pH would require some additional circuits (Amplification, Signal conditioning, Analog to digital conversion, etc)..."

**Comment by IvanFengJK** [comment]
pH Sensor Kit
http://atlas-scientific.com/product_pages/kits/ph-kit.html
https://www.sparkfun.com/products/10972
They are relatively expensive but you can see what they use and see what would really be needed.

**Comment by Swordwrath** [comment]
http://dfrobot.com/wiki/index.php/PH_meter(SKU:_SEN0161)


http://www.dfrobot.com/index.php?route=product/product&product_id=1025#.V32zqHQZ7qA

**Comment by fishnsotong** [comment]
http://www.dfrobot.com/index.php?route=product/product&product_id=1110&search=ph&description=true#.V35zuPT0qnM


This one seems to be $60 and can withstand long exposures to an aquatic medium. Your thoughts?

**Comment by fishnsotong** [comment]
I assume that everybody knows that we have bought the above. Thanks all.
